apiVersion: v1
kind: Secret
metadata:
  name: {{ include "order.fullname" . }}-secrets
type: Opaque
data:
  appUsername: {{.Values.order.appUsername|b64enc}}      #b3R1c3VzZXI= #otususer
  appPassword: {{.Values.order.appPassword|b64enc}}  #b3R1c3VzZXI= #otususer
  appDbUrl: {{.Values.order.appDbUrl|b64enc}}        #amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtc2VydmljZTo1NDMyL290dXNkYg== #jdbc:postgresql://postgres-service:5432/otusdb

     